# Generated by Django 6.0.4 on 2026-05-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_manager', '0002_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=35)),
                ('pseudonym', models.CharField(max_length=20)),
                ('biography', models.TextField(null=True)),
                ('email', models.EmailField(max_length=75)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='discounted_price',
            field=models.FloatField(null=True),
        ),
    ]
