# Generated by Django 6.0.4 on 2026-05-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_manager', '0004_author_website_alter_author_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='comments_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='followers_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='monetisation_income',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='posts_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='reputation_score',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
