# Generated by Django 6.0.4 on 2026-05-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_manager', '0005_remove_author_biography_remove_author_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bio',
            new_name='biography',
        ),
    ]
